# Ensure this cmd is run from within the playbook dir:
#  ansible-playbook -i ../devbox.ini -u james devbox.yml -K 
# TODO: how to store become password in vault?

- hosts: all

  vars_files:
  - vars/devboxtemp.yml

  vars:
   # not included: 'qemu-system', 'qemu-user-static',
   sys_packages: [ 'curl', 'vim', 'git', 'nfs-common', 'tmux', 'build-essential', 'manpages-dev',  'python3-pip', 'mc', 'net-tools', 'shellcheck' ]

  tasks:
  # Install Packages
    - name: Update apt-get repo and cache
      become: true
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all apt packages
      become: true
      apt: upgrade=dist force_apt_get=yes

    - name: Install required system packages
      become: true
      apt: name={{ sys_packages }} state=latest

    # Zsh
    - name: Zsh-ohmyzsh
      include_role:
        name: gantsign.oh-my-zsh
      vars:
        ansible_become: yes
        users:
          - username: "{{ ansible_user_id }}" #TODO can this be removed and use user instead in substitutions?
            oh_my_zsh:
              theme: awesomepanda
              plugins:
                - git

  # enable completion for bash and zsh styles
    - name: compinit for bash and zsh completion
      ansible.builtin.blockinfile:
       path: "{{ ansible_user_dir }}/.zshrc"
       block: |
        autoload -Uz compinit bashcompinit
        compinit
        bashcompinit
  # Install pip3 local package support
    - name: pip3 local binary resolution eg for ansible
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.zshrc"
        line: 'export PATH=$PATH:$HOME/.local/bin'
        insertafter: EOF

  # Install Ansible
    - name: install ansible with pip3
      ansible.builtin.command: pip3 install ansible --user
      changed_when: false
      register: ans_output
      failed_when: ans_output.rc != 0

  # Install precommit
    - name: install pre-commit
      ansible.builtin.command: pip3 install pre-commit --user
      changed_when: false
      register: precm_output
      failed_when: precm_output.rc != 0

    - name: Copy TMUX config
      copy:
        src: "{{ playbook_dir }}/files/dotfiles/.tmux.conf"
        dest: "{{ ansible_user_dir }}/.tmux.conf"
        backup: no
        group: "{{ ansible_user_id }}"
        owner: "{{ ansible_user_id }}"
        mode: 0700

    - name: SSHagent
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.zshrc"
        line: 'eval $(ssh-agent -s)'
        insertafter: EOF

- name: az cli
  import_playbook: playbooktemp/azcli.yml

- name: gh
  import_playbook: playbooktemp/gh.yml

- name: dotnet6
  import_playbook: playbooktemp/dotnet6.yml

- name: kubectl
  import_playbook: playbooktemp/kubectl.yml

- name: golang
  import_playbook: playbooktemp/golang.yml

- name: cloudflared
  import_playbook: playbooktemp/cloudflared.yml

- name: vim
  import_playbook: playbooktemp/vim.yml

  # TODO make this conditional based on a tag:
- name: code-server
  import_playbook: playbooktemp/code-server.yml

- name: azdevcli
  import_playbook: playbooktemp/azdevcli.yml

- name: helm
  import_playbook: playbooktemp/helm.yml

- name: kind
  import_playbook: playbooktemp/kind.yml

- name: misc
  import_playbook: playbooktemp/misc.yml

- name: checkreboot
  import_playbook: playbooktemp/checkreboot.yml

# Look at kind vs minikube for azure thing
# ensure compose with private
# verify build of previewd
