---
- hosts: all
  vars_files:
  - ../vars/devboxtemp.yml
  tasks:
# install az dev cli
    - name: Download azure dev cli
      get_url:
        url: https://aka.ms/install-azd.sh
        dest: "{{ download_dir }}/install-azd.sh"
        mode: 0754

    - name: Run setup for azd
      command: /tmp/install-azd.sh
      args:
        chdir: "{{ download_dir }}"
        creates: /usr/local/bin/azd