---
- hosts: all
  become: true
# install cloudflared
  tasks:
    - name: Cloudflared
      block:
        - name: cloudflared pgpkey
          ansible.builtin.get_url:
            url: https://pkg.cloudflare.com/cloudflare-main.gpg
            dest: /usr/share/keyrings/cloudflare-main.gpg

        - name: cloudflared package
          ansible.builtin.apt_repository:
            repo: "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared focal main"
            state: present

        - name: install cloudflared
          apt: 
            name: cloudflared
            update_cache: yes
