---
- hosts: all
  vars_files:
  - ../vars/devboxtemp.yml
  vars:
   docker_packages: [ 'qemu-system', 'qemu-user-static']
  tasks:
    - name: Install docker dependencies
      become: true
      apt: name={{ docker_packages }} state=latest

    - name: docker pgpkey
      become: true
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: docker repo
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
        state: present

    - name: Install docker
      become: true
      apt: 
        update_cache: yes
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin

    - name: Docker usergroup
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: "docker"
        append: yes
