---
- hosts: all
  vars_files:
  - ../vars/devboxtemp.yml
  tasks:
# install .net 6
    - name: Download .NET6 debian package
      become: true
      get_url:
        url: "https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb"
        dest: "{{ download_dir }}"

    - name: Install a .deb package from the internet
      become: true
      ansible.builtin.apt:
        deb: "{{ download_dir }}/packages-microsoft-prod.deb"

    - name: Install dotnet6 sdk
      become: true
      apt: 
        name: dotnet-sdk-6.0
        update_cache: yes

    - name: dotnet autocomplete
      ansible.builtin.blockinfile:
       path: "{{ ansible_user_dir }}/.zshrc"
       block: |
        _dotnet_zsh_complete()
        {
          local completions=("$(dotnet complete "$words")")
        
          reply=( "${(ps:\n:)completions}" )
        }

        compctl -K _dotnet_zsh_complete dotnet
