---
- hosts: all
  tasks:
# install gh
    - name: gh
      block:
        - name: github pgpkey
          ansible.builtin.get_url:
            url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
            dest: /etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg

        - name: gh repo
          ansible.builtin.apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
            state: present

        - name: Install gh
          become: true
          apt: 
            name: gh
            update_cache: yes

        - name: Install gh autocompletion
          command: "sudo bash -c 'gh completion -s zsh > /usr/local/share/zsh/site-functions/_gh'"
          args:
            creates: /usr/local/share/zsh/site-functions/_gh