---
- hosts: all
  tasks:
    - name: Download and Expand Go
      become: true
      unarchive:
        remote_src: yes
        src: "https://go.dev/dl/go1.18.4.linux-amd64.tar.gz"
        dest: "{{ local_dir }}"
        creates: "{{ golang_dir }}"

    - name: Ensure golang in path
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.zshrc"
        line: 'export PATH={{ golang_dir }}/bin:$PATH'
        insertafter: EOF

    - name: Ensure golang local binaries in path
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.zshrc"
        line: 'export PATH=$PATH:$HOME/go/bin'
        insertafter: EOF