# ansible-playbook -i localhost, --connection=local playbooktemp/golang.yml -K
---
- hosts: all
  vars_files:
  - "{{ playbook_dir }}/../vars/default.yml"
  tasks:
    - name: Download and Expand Go
      become: true
      unarchive:
        remote_src: yes
        src: "https://go.dev/dl/go1.20.4.linux-amd64.tar.gz"
          
        dest: "{{ local_dir }}"
        creates: "{{ golang_dir }}"

    - name: Ensure golang in path
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.zshrc"
        line: 'export PATH={{ golang_dir }}/bin:$PATH'
        insertafter: EOF

    - name: Ensure golang local binaries in path
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.zshrc"
        line: 'export PATH=$PATH:$HOME/go/bin'
        insertafter: EOF

    - name: golang install commands
      # if this works it's because become was removed
      ansible.builtin.command: "/usr/local/go/bin/go install {{ item }}"
      changed_when: false
      register: ans_output
      failed_when: ans_output.rc != 0
      with_items: 
       - "github.com/golangci/golangci-lint/cmd/golangci-lint@latest"
       - "github.com/uw-labs/strongbox@v1.0.0"
       - "sigs.k8s.io/kind@latest"
       - "github.com/homeport/dyff/cmd/dyff@latest"
       - "github.com/spf13/cobra-cli@latest"
       - "github.com/client9/misspell/cmd/misspell@latest"
       - "sigs.k8s.io/kind@v0.14.0"
       - "honnef.co/go/tools/cmd/staticcheck@latest"
       - "github.com/derailed/popeye@latest"
       - "github.com/go-delve/delve/cmd/dlv@latest"
       - "cuelang.org/go/cmd/cue@latest"
       - "github.com/goreleaser/goreleaser@latest"
       - "github.com/cheat/cheat/cmd/cheat@latest"
         #       - "github.com/goreleaser/goreleaser@latest"
