---
- hosts: all
  tasks:
    - name: install passlib
      ansible.builtin.command: pip3 install passlib --user
      changed_when: false
      register: ans_output
      failed_when: ans_output.rc != 0

    - name: mosh
      include_role:
        name: andrewrothstein.mosh

    - name: k9s
      include_role:
        name: andrewrothstein.k9s

    - name: yq
      include_role:
        name: andrewrothstein.yq

    - name: jq
      include_role:
        name: andrewrothstein.jq

    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh
