---
- hosts: all
  vars_files:
  - ../vars/devboxtemp.yml
  vars:
   podman_packages: [ 'podman', 'qemu-system', 'qemu-user-static']
  tasks:
    - name: Install podman and friends
      become: true
      apt: name={{ podman_packages }} state=latest
    - name: Download
      become: true
      ansible.builtin.get_url:
        src: "https://github.com/containers/gvisor-tap-vsock/releases/download/v0.4.0/gvproxy-linux"
        dest: "/usr/libexec/podman/gvproxy"
    - name: Install podman completion
      become: true
      command: "sudo bash -c 'podman completion -f /usr/local/share/zsh/site-functions/_podman zsh'"
      args:
        creates: /usr/local/share/zsh/site-functions/_podman
