#ansible-playbook -i ../inventory/hosts_for_monitoring.ini userssh.yml -u root --extra-vars "uusername=<USERNAME>" --extra-vars "upassword=<PASSWORD>"
---
- hosts: all
 
  tasks:
    - name: Creating user "{{ uusername }}" with admin access
      user: 
        name: "{{ uusername }}"
        password: "{{ upassword | password_hash('sha512') }}"
        groups: adm,sudo
        append: yes
    - name: Set authorized keys taken from url
      ansible.posix.authorized_key:
        user: "{{ uusername }}"
        state: present
        key: "{{ repokeys }}"
