#ansiblk-playbook makehost-do.yml
---
- hosts: all
 
  vars_files:
       - ../vars/default.yml 
  tasks:
    - name: Creating user "{{ uusername }}" with admin access
      user: 
        name: {{ uusername }}
        password: {{ upassword | password_hash('sha512') }}
        groups: admin append=yes
