#ansible-playbook -i ../inventory/hosts_for_monitoring.ini userssh.yml -u root --extra-vars "uusername=<USERNAME>" --extra-vars "upassword=<PASSWORD>"
---
- hosts: master
  remote_user: root
  gather_facts: false 
  tasks:
    - name: Wait 600 seconds for target connection to become reachable/usable
      ansible.builtin.wait_for_connection:

    - name: Creating user "{{ uusername }}" with admin access
      become: true
      user: 
        name: "{{ uusername }}"
        password: "{{ upassword | password_hash('sha512') }}"
        groups: adm,sudo
        shell: /bin/bash
        append: yes

    - name: Set authorized keys taken from url
      become: true
      ansible.posix.authorized_key:
        user: "{{ uusername }}"
        state: present
        key: "{{ repokeys }}"

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ copy_local_key }}"

    - name: Disallow password authentication
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PasswordAuthentication"
                  line="PasswordAuthentication no"
                  state=present
      notify: Restart ssh

    - name: Disallow root SSH access
      lineinfile: dest=/etc/ssh/sshd_config
                  regexp="^PermitRootLogin"
                  line="PermitRootLogin no"
                  state=present
      notify: Restart ssh
  # restart ssh
  handlers:
    - name: Restart ssh
      service: name=ssh state=restarted

